const notas = [
    new Nota('c1', 'z'),
    new Nota('cs1', 's'),
    new Nota('d1', 'x'),
    new Nota('eb1', 'd'),
    new Nota('e1', 'c'),
    new Nota('f1', 'v'),
    new Nota('fs1', 'g'),
    new Nota('g1', 'b'),
    new Nota('gs1', 'h'),
    new Nota('a1', 'n'),
    new Nota('bb1', 'j'),
    new Nota('b1', 'm'),
    new Nota('c2', 'q'),
    new Nota('cs2', '2'),
    new Nota('d2', 'w'),
    new Nota('eb2', '3'),
    new Nota('e2', 'e'),
    new Nota('f2', 'r'),
    new Nota('fs2', '5'),
    new Nota('g2', 't'),
    new Nota('gs2', '6'),
    new Nota('a2', 'y'),
    new Nota('bb2', '7'),
    new Nota('b2', 'u')
];